
server:
  port: 81
spring:
  mvc:
    view:
      suffix: .html
      prefix: /
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: ${zipkin.url:http://192.168.99.100:9411/}
  cloud:
    bus:
      destination: configXchange
  rabbitmq:
    host: ${rabbitmq.host:192.168.99.100}
    port: ${rabbitmq.port:5672}
    
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    metadata-map:
      zone: A
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: ${apigateway.eureka.url:http://192.168.99.100:8761/eureka}
management:
  endpoints:
    web:
      exposure:
        include: "*"
