spring:
  cloud:
    config:
      server:
        git:
          uri: ${configserver.git.url:https://github.ibm.com/soorajshettyv/LabsConfig.git}
          username: ${configserver.git.username:soorajshettyv@in.ibm.com}
          password: ${configserver.git.pass:d135c2753cac98adcb1bf576b3f3cd5e2c43ef0f}
          clone-on-start: ${configserver.git.cloneonstart:true}
    bus:
      destination: configXchange
  rabbitmq:
    host: ${rabbitmq.host:192.168.99.100}
    port: ${rabbitmq.port:5672}
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"

