--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: webauditms
    version: v1
  name: webauditms
spec: 
  ports: 
    - 
      name: http
      port: 8077
      targetPort: 8077
  selector: 
    app: webauditms
    version: v1
  type: NodePort